### ISSUE TITLE
Navigation system is buggy in Playground

### ISSUE THREAD

**Issue by axel7083** [projectatomic/ai-studio#226] opened 2024-02-05 10:03 UTC
When using the `Navigate to container` and go back to the Studio, we have some empty pages when navigating

https://github.com/projectatomic/ai-studio/assets/42176370/1086df02-f0a4-4ace-a9c4-dc5e2a371918

**Comment by slemeur** [comment] 2024-03-08 16:09
Closing - cannot reproduce

**Closed by slemeur** 2024-03-08 16:09 UTC
Labels: kind/bug, area/playground
